### ISSUE TITLE
cannot set latency over 300

### ISSUE THREAD

**Issue by rhetr** [ravenium/srt-live-server#8]
i want to set latency over 300 but whenever I do so I am unable to stream to srt-live-server. not sure if this is an issue with the docker container or with srt-live-server itself.

**Comment by ravenium** [comment]
In theory the app will just take whatever parameters you place into the .conf file.  Have you tried verifying the latency with docker log?

If you're looking for something a bit more oft-updated I'd suggest srtrelay, which is written and maintained in golang.  I made a dockerization of it [here](https://github.com/ravenium/srtrelay).

**Comment by yginuo** [comment]
I also had this problem, when I set the latency above 300, the docker container couldn't start.

**Comment by ravenium** [comment]
I did a quick bit of digging:

```srt-live-server-srt-1  | 2022-07-08 22:42:54:542 SLS ERROR: line:16, set failed, out of range, name='latency', value='301'.```

This is because there is a function, SLS_SET_CONF, that is checking to make sure the config value of latency is between 1 and 300.  Your best bet is to change the value to something higher, though no guarantees if the author had an overriding reason for limiting it as such.

I would still say the best bet is to use voc/srtrelay as it's a bit more current and tidier.
